//
// Generated file, do not edit! Created by nedtool 4.6 from AppMessages/MobilityAppMessage.msg.
//

#ifndef _MOBILITYAPPMESSAGE_M_H_
#define _MOBILITYAPPMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>AppMessages/MobilityAppMessage.msg:17</tt> by nedtool.
 * <pre>
 * packet MobilityAppMessage
 * {
 *     string contents[];
 * }
 * </pre>
 */
class MobilityAppMessage : public ::cPacket
{
  protected:
    opp_string *contents_var; // array ptr
    unsigned int contents_arraysize;

  private:
    void copy(const MobilityAppMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MobilityAppMessage&);

  public:
    MobilityAppMessage(const char *name=NULL, int kind=0);
    MobilityAppMessage(const MobilityAppMessage& other);
    virtual ~MobilityAppMessage();
    MobilityAppMessage& operator=(const MobilityAppMessage& other);
    virtual MobilityAppMessage *dup() const {return new MobilityAppMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setContentsArraySize(unsigned int size);
    virtual unsigned int getContentsArraySize() const;
    virtual const char * getContents(unsigned int k) const;
    virtual void setContents(unsigned int k, const char * contents);
};

inline void doPacking(cCommBuffer *b, MobilityAppMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MobilityAppMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MOBILITYAPPMESSAGE_M_H_

